import { PropsWithChildren, Suspense } from "react";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const robotoSans = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function AppProviders({ children }: PropsWithChildren) {
  const [locale, messages] = await Promise.all([getLocale(), getMessages()]);

  return (
    <NextIntlClientProvider messages={messages} locale={locale}>
      {children}
      <Toaster richColors position="top-right" />
    </NextIntlClientProvider>
  );
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${robotoSans.variable} h-full antialiased`}
    >
      <body className="font-sans">
        <Suspense>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
          >
            <AppProviders>{children}</AppProviders>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
