type Skill {
  id: ID!
  name: String!
  categoryId: ID
  categoryName: String
}

type Language {
  id: ID!
  name: String!
  iso2: String
}

type Project {
  id: ID!
  name: String!
  internalName: String
  description: String
  domain: String
  startDate: String
  endDate: String
  environment: [String!]
}

type CvProject {
  id: ID!
  startDate: String
  endDate: String
  responsibilities: [String!]
  project: Project!
}

type CV {
  id: ID!
  title: String!
  fullname: String!
  email: String!
  education: String
  description: String
  skills: [Skill!]
  languages: [Language!]
  projects: [CvProject!]
  userId: ID
}

input CVInput {
  title: String!
  fullname: String!
  education: String
  description: String
  email: String!
}

input CVUpdateInput {
  id: ID!
  title: String
  fullname: String
  education: String
  description: String
  email: String
}

input SkillInput {
  name: String!
  categoryId: ID
  mastery: String
}

input ProjectInput {
  id: ID
  name: String!
  domain: String
  startDate: String
  endDate: String
  description: String
  responsibilities: [String!]
  environment: [String!]
}

type Query {
  CVs: [CV!]!
  cv(id: ID!): CV
  skills: [Skill!]
  projects: [Project!]
}

type Mutation {
  createCV(cv: CVInput!): CV!
  updateCV(cv: CVUpdateInput!): CV!
  deleteCV(id: ID!): Int!
  updateCVSkills(id: ID!, skills: [SkillInput!]!): CV!
  upsertCvProject(cvId: ID!, project: ProjectInput!): CvProject!
  deleteCvProject(cvId: ID!, cvProjectId: ID!): Int!
}