type CV {
  id: ID!
  title: String!
  fullname: String!
  education: String!
  description: String!
  email: String!
}

input CVInput {
  title: String!
  fullname: String!
  education: String!
  description: String!
  email: String!
}

input CVUpdateInput {
  id: ID!
  title: String
  fullname: String
  education: String
  description: String
  email: String!
}

type Query {
  CVs: [CV!]!
}

type Mutation {
  createCV(cv: CVInput!): CV!
  updateCV(cv: CVUpdateInput!): CV!
  deleteCV(id: ID!): Int!
}